menu:
    兑吧资讯: /
    关于: /about/

favicon: http://yun.duiba.com.cn/logo.png
logo: http://yun.duiba.com.cn/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Copyright Infomation
startyear: 2015
